# Generated by Django 2.2 on 2019-04-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
