# Generated by Django 2.2 on 2019-04-18 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publication_date', models.DateField(default=datetime.date(2019, 4, 18))),
            ],
            options={
                'db_table': 'Book1',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
